name: Deploy static content to Pages

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.13
            - run: python -m pip install -r requirements.txt
            - run: python check.py
            - uses: actions/setup-node@v4
              with:
                  node-version: 24.6.0
            - run: npm install
              working-directory: ui
            - run: npm run build
              working-directory: ui
            - run: npm run build-standalone
              working-directory: ui
            - uses: actions/configure-pages@v5
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: "ui/build"
            - uses: actions/deploy-pages@v4
              id: deployment
